"""Add is_active column to stores table

Revision ID: fa25ea1c2477
Revises: b1891f56b4aa
Create Date: 2026-01-10 15:17:23.931091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa25ea1c2477'
down_revision: Union[str, Sequence[str], None] = 'b1891f56b4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_changes_server_seq'), 'changes', ['server_seq'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.drop_index(op.f('idx_sales_transaction_number'), table_name='sales')
    op.create_index(op.f('ix_sales_transaction_number'), 'sales', ['transaction_number'], unique=False)
    
    # Add missing is_active column to stores table
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_transaction_number'), table_name='sales')
    op.create_index(op.f('idx_sales_transaction_number'), 'sales', ['transaction_number'], unique=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_changes_server_seq'), table_name='changes')
    
    # Remove is_active column from stores table
    op.drop_column('stores', 'is_active')
    # ### end Alembic commands ###
